<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.8" />
		<PackageReference Include="System.Runtime.Caching" Version="10.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.8" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\RotoMonster.Core\RotoMonster.Core.csproj" />
		<ProjectReference Include="..\..\RotoMonsterExternalAPIs\RotoMonsterExternalAPIs.Client.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Migrations\" />
		<Folder Include="RMSqlData\" />
	</ItemGroup>

</Project>
