// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RotoMonster.Data;

namespace RotoMonster.Data.Migrations
{
    [DbContext(typeof(RMDBContext))]
    [Migration("20200323072704_dord1")]
    partial class dord1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RotoMonster.Core.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool?>("ExcludeFromEase")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCalculated")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPositive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStat")
                        .HasColumnType("bit");

                    b.Property<string>("PerDisplayFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Property")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalDisplayFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("UseAsValue")
                        .HasColumnType("bit");

                    b.Property<int?>("WeightCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerTypeId");

                    b.HasIndex("WeightCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("RotoMonster.Core.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("RotoMonster.Core.FantasyProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FantasyProviders");
                });

            modelBuilder.Entity("RotoMonster.Core.FantasyProviderPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FantasyProviderId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("ProviderId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FantasyProviderId");

                    b.HasIndex("PlayerId");

                    b.ToTable("FantasyProviderPlayers");
                });

            modelBuilder.Entity("RotoMonster.Core.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GameTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("int");

                    b.Property<string>("SportRadarId")
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("RotoMonster.Core.MLBHitterGame", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<byte>("AB")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Assists")
                        .HasColumnType("tinyint");

                    b.Property<byte>("BB")
                        .HasColumnType("tinyint");

                    b.Property<byte>("BattingOrder")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Doubles")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Errors")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FullInnings")
                        .HasColumnType("tinyint");

                    b.Property<byte>("GIDP")
                        .HasColumnType("tinyint");

                    b.Property<byte>("GrandSlams")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HBP")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HR")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Hits")
                        .HasColumnType("tinyint");

                    b.Property<byte>("K")
                        .HasColumnType("tinyint");

                    b.Property<byte>("LOB")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PA")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PastBalls")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Putouts")
                        .HasColumnType("tinyint");

                    b.Property<byte>("R")
                        .HasColumnType("tinyint");

                    b.Property<byte>("RBI")
                        .HasColumnType("tinyint");

                    b.Property<byte>("RBITwoOut")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SB")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SBCaught")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SacBunts")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SacFlies")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Singles")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Starts")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ThirdInnings")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Triples")
                        .HasColumnType("tinyint");

                    b.HasKey("PlayerId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("MLBHitterGames");
                });

            modelBuilder.Entity("RotoMonster.Core.MLBPitcherGame", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<byte>("AtBatsAgainst")
                        .HasColumnType("tinyint");

                    b.Property<byte>("BB")
                        .HasColumnType("tinyint");

                    b.Property<byte>("BBI")
                        .HasColumnType("tinyint");

                    b.Property<byte>("BS")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Balks")
                        .HasColumnType("tinyint");

                    b.Property<byte>("BoxscoreOrder")
                        .HasColumnType("tinyint");

                    b.Property<byte>("CG")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Doubles")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FullInnings")
                        .HasColumnType("tinyint");

                    b.Property<byte>("GamesFinished")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HBP")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HR")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HitsAllowed")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Holds")
                        .HasColumnType("tinyint");

                    b.Property<byte>("InheritedRunners")
                        .HasColumnType("tinyint");

                    b.Property<byte>("InheritedRunnersScored")
                        .HasColumnType("tinyint");

                    b.Property<byte>("K")
                        .HasColumnType("tinyint");

                    b.Property<byte>("L")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Outs")
                        .HasColumnType("tinyint");

                    b.Property<byte>("OutsFlyBalls")
                        .HasColumnType("tinyint");

                    b.Property<byte>("OutsGroundBalls")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PickOffs")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Pitches")
                        .HasColumnType("tinyint");

                    b.Property<byte>("QS")
                        .HasColumnType("tinyint");

                    b.Property<byte>("RunsAgainst")
                        .HasColumnType("tinyint");

                    b.Property<byte>("RunsEarned")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SacBunts")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SacFlies")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Shutouts")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Singles")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Strikes")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ThirdInnings")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Triples")
                        .HasColumnType("tinyint");

                    b.Property<byte>("W")
                        .HasColumnType("tinyint");

                    b.Property<byte>("WildPitches")
                        .HasColumnType("tinyint");

                    b.HasKey("PlayerId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("MLBPitcherGames");
                });

            modelBuilder.Entity("RotoMonster.Core.NBAPlayerGame", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<byte>("Assists")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Blocks")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DefensiveRebounds")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DoubleDoubles")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FieldGoals")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FieldGoalsAttempted")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("FoulTrouble")
                        .HasColumnType("bit");

                    b.Property<byte>("Fouls")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FreeThrows")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FreeThrowsAttempted")
                        .HasColumnType("tinyint");

                    b.Property<double>("Minutes")
                        .HasColumnType("float");

                    b.Property<byte>("OffensiveRebounds")
                        .HasColumnType("tinyint");

                    b.Property<double>("PlusMinus")
                        .HasColumnType("float");

                    b.Property<byte>("Points")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Started")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Steals")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Technicals")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Threes")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ThreesAttempted")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TripleDoubles")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Turnovers")
                        .HasColumnType("tinyint");

                    b.Property<double?>("Usage")
                        .HasColumnType("float");

                    b.Property<byte>("Wins")
                        .HasColumnType("tinyint");

                    b.HasKey("PlayerId", "GameId");

                    b.ToTable("NBAPlayerGames");
                });

            modelBuilder.Entity("RotoMonster.Core.PerValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("PlayerTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PlayerTypeId");

                    b.ToTable("PerValues");
                });

            modelBuilder.Entity("RotoMonster.Core.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<int?>("PickNumber")
                        .HasColumnType("int");

                    b.Property<int?>("RookieYear")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("RotoMonster.Core.PlayerAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerAliases");
                });

            modelBuilder.Entity("RotoMonster.Core.PlayerDefaultPosition", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("PlayerDefaultPositions");
                });

            modelBuilder.Entity("RotoMonster.Core.PlayerGame", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NotPlayingDescription")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NotPlayingReason")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool?>("Played")
                        .HasColumnType("bit");

                    b.Property<bool?>("Started")
                        .HasColumnType("bit");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("PlayerGames");
                });

            modelBuilder.Entity("RotoMonster.Core.PlayerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DefaultPerTeam")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("PluralTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SingularTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlayerTypes");
                });

            modelBuilder.Entity("RotoMonster.Core.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int?>("PlayerTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerTypeId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("RotoMonster.Core.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRegularSeason")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YahooId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("RotoMonster.Core.SeasonDivision", b =>
                {
                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.HasKey("SeasonId", "DivisionId");

                    b.HasIndex("DivisionId");

                    b.ToTable("SeasonDivisions");
                });

            modelBuilder.Entity("RotoMonster.Core.SeasonPlayer", b =>
                {
                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("SeasonId", "PlayerId", "PlayerTypeId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerTypeId");

                    b.ToTable("SeasonPlayers");
                });

            modelBuilder.Entity("RotoMonster.Core.SeasonTeam", b =>
                {
                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.HasKey("SeasonId", "TeamId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("TeamId");

                    b.ToTable("SeasonTeams");
                });

            modelBuilder.Entity("RotoMonster.Core.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("RotoMonster.Core.Category", b =>
                {
                    b.HasOne("RotoMonster.Core.PlayerType", "PlayerType")
                        .WithMany()
                        .HasForeignKey("PlayerTypeId");

                    b.HasOne("RotoMonster.Core.Category", "WeightCategory")
                        .WithMany()
                        .HasForeignKey("WeightCategoryId");
                });

            modelBuilder.Entity("RotoMonster.Core.FantasyProviderPlayer", b =>
                {
                    b.HasOne("RotoMonster.Core.FantasyProvider", "FantasyProvider")
                        .WithMany()
                        .HasForeignKey("FantasyProviderId");

                    b.HasOne("RotoMonster.Core.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("RotoMonster.Core.Game", b =>
                {
                    b.HasOne("RotoMonster.Core.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId");

                    b.HasOne("RotoMonster.Core.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId");

                    b.HasOne("RotoMonster.Core.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId");
                });

            modelBuilder.Entity("RotoMonster.Core.MLBHitterGame", b =>
                {
                    b.HasOne("RotoMonster.Core.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.MLBPitcherGame", b =>
                {
                    b.HasOne("RotoMonster.Core.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.PerValue", b =>
                {
                    b.HasOne("RotoMonster.Core.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.PlayerType", "PlayerType")
                        .WithMany()
                        .HasForeignKey("PlayerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.PlayerAlias", b =>
                {
                    b.HasOne("RotoMonster.Core.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("RotoMonster.Core.PlayerDefaultPosition", b =>
                {
                    b.HasOne("RotoMonster.Core.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.PlayerGame", b =>
                {
                    b.HasOne("RotoMonster.Core.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.Position", b =>
                {
                    b.HasOne("RotoMonster.Core.PlayerType", "PlayerType")
                        .WithMany()
                        .HasForeignKey("PlayerTypeId");
                });

            modelBuilder.Entity("RotoMonster.Core.SeasonDivision", b =>
                {
                    b.HasOne("RotoMonster.Core.Division", null)
                        .WithMany("SeasonDivisions")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Season", null)
                        .WithMany("Divisions")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.SeasonPlayer", b =>
                {
                    b.HasOne("RotoMonster.Core.Player", null)
                        .WithMany("SeasonPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.PlayerType", null)
                        .WithMany("SeasonPlayers")
                        .HasForeignKey("PlayerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Season", null)
                        .WithMany("SeasonPlayers")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.SeasonTeam", b =>
                {
                    b.HasOne("RotoMonster.Core.Division", null)
                        .WithMany("SeasonTeams")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Season", null)
                        .WithMany("SeasonTeams")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Team", null)
                        .WithMany("SeasonTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
