// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RotoMonster.Data;

namespace RotoMonster.Data.Migrations
{
    [DbContext(typeof(RMDBContext))]
    [Migration("20200426210131_d10")]
    partial class d10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RotoMonster.Core.ActiveRosterSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DefaultNumberOf")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActiveRosterSpots");
                });

            modelBuilder.Entity("RotoMonster.Core.ActiveRosterSpotPosition", b =>
                {
                    b.Property<int>("ActiveRosterSpotId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("ActiveRosterSpotId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("ActiveRosterSpotPositions");
                });

            modelBuilder.Entity("RotoMonster.Core.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CBSId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ESPNId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ExcludeFromEase")
                        .HasColumnType("bit");

                    b.Property<string>("FanTraxId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPositive")
                        .HasColumnType("bit");

                    b.Property<string>("OtherAbbreviations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerDisplayFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SourceField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalDisplayFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("UseAsValue")
                        .HasColumnType("bit");

                    b.Property<int?>("WeightCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("YahooId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerTypeId");

                    b.HasIndex("WeightCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("RotoMonster.Core.DisplayCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsAfterStats")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBeforeStats")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("DisplayCategories");
                });

            modelBuilder.Entity("RotoMonster.Core.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("RotoMonster.Core.Draft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DraftDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FantasyProviderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAuction")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMoney")
                        .HasColumnType("bit");

                    b.Property<int>("LeagueSize")
                        .HasColumnType("int");

                    b.Property<string>("LeagueType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderLeagueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FantasyProviderId");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("RotoMonster.Core.DraftPlayer", b =>
                {
                    b.Property<int>("DraftId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("DraftOrder")
                        .HasColumnType("int");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProviderTeamId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DraftId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("DraftPlayers");
                });

            modelBuilder.Entity("RotoMonster.Core.FantasyProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FantasyProviders");
                });

            modelBuilder.Entity("RotoMonster.Core.FantasyProviderPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FantasyProviderId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("ProviderId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FantasyProviderId");

                    b.HasIndex("PlayerId");

                    b.ToTable("FantasyProviderPlayers");
                });

            modelBuilder.Entity("RotoMonster.Core.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GameTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("int");

                    b.Property<string>("SportRadarId")
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("RotoMonster.Core.MLBHitterGame", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<byte>("AB")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Assists")
                        .HasColumnType("tinyint");

                    b.Property<byte>("BB")
                        .HasColumnType("tinyint");

                    b.Property<byte>("BattingOrder")
                        .HasColumnType("tinyint");

                    b.Property<byte>("CS")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Doubles")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Errors")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FullInnings")
                        .HasColumnType("tinyint");

                    b.Property<byte>("GIDP")
                        .HasColumnType("tinyint");

                    b.Property<byte>("GrandSlams")
                        .HasColumnType("tinyint");

                    b.Property<byte>("H")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HBP")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HR")
                        .HasColumnType("tinyint");

                    b.Property<byte>("K")
                        .HasColumnType("tinyint");

                    b.Property<byte>("LOB")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PA")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PastBalls")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Putouts")
                        .HasColumnType("tinyint");

                    b.Property<byte>("R")
                        .HasColumnType("tinyint");

                    b.Property<byte>("RBI")
                        .HasColumnType("tinyint");

                    b.Property<byte>("RBITwoOut")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SB")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SacBunts")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SacFlies")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Singles")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Starts")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ThirdInnings")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Triples")
                        .HasColumnType("tinyint");

                    b.HasKey("PlayerId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("MLBHitterGames");
                });

            modelBuilder.Entity("RotoMonster.Core.MLBPitcherGame", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<byte>("AtBatsAgainst")
                        .HasColumnType("tinyint");

                    b.Property<byte>("BB")
                        .HasColumnType("tinyint");

                    b.Property<byte>("BBI")
                        .HasColumnType("tinyint");

                    b.Property<byte>("BS")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Balks")
                        .HasColumnType("tinyint");

                    b.Property<byte>("BoxscoreOrder")
                        .HasColumnType("tinyint");

                    b.Property<byte>("CG")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Doubles")
                        .HasColumnType("tinyint");

                    b.Property<byte>("GamesFinished")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HBP")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HR")
                        .HasColumnType("tinyint");

                    b.Property<byte>("HitsAllowed")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Holds")
                        .HasColumnType("tinyint");

                    b.Property<byte>("InheritedRunners")
                        .HasColumnType("tinyint");

                    b.Property<byte>("InheritedRunnersScored")
                        .HasColumnType("tinyint");

                    b.Property<double>("Innings")
                        .HasColumnType("float");

                    b.Property<byte>("K")
                        .HasColumnType("tinyint");

                    b.Property<byte>("L")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Outs")
                        .HasColumnType("tinyint");

                    b.Property<byte>("OutsFlyBalls")
                        .HasColumnType("tinyint");

                    b.Property<byte>("OutsGroundBalls")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PickOffs")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Pitches")
                        .HasColumnType("tinyint");

                    b.Property<byte>("QS")
                        .HasColumnType("tinyint");

                    b.Property<byte>("RunsAgainst")
                        .HasColumnType("tinyint");

                    b.Property<byte>("RunsEarned")
                        .HasColumnType("tinyint");

                    b.Property<byte>("S")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SacBunts")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SacFlies")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Shutouts")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Singles")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Strikes")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Triples")
                        .HasColumnType("tinyint");

                    b.Property<byte>("W")
                        .HasColumnType("tinyint");

                    b.Property<byte>("WildPitches")
                        .HasColumnType("tinyint");

                    b.HasKey("PlayerId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("MLBPitcherGames");
                });

            modelBuilder.Entity("RotoMonster.Core.NBAPlayerGame", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<byte>("Assists")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Blocks")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DefensiveRebounds")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DoubleDoubles")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FieldGoals")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FieldGoalsAttempted")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("FoulTrouble")
                        .HasColumnType("bit");

                    b.Property<byte>("Fouls")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FreeThrows")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FreeThrowsAttempted")
                        .HasColumnType("tinyint");

                    b.Property<double>("Minutes")
                        .HasColumnType("float");

                    b.Property<byte>("OffensiveRebounds")
                        .HasColumnType("tinyint");

                    b.Property<double>("PlusMinus")
                        .HasColumnType("float");

                    b.Property<byte>("Points")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Started")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Steals")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Technicals")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Threes")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ThreesAttempted")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TripleDoubles")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Turnovers")
                        .HasColumnType("tinyint");

                    b.Property<double?>("Usage")
                        .HasColumnType("float");

                    b.Property<byte>("Wins")
                        .HasColumnType("tinyint");

                    b.HasKey("PlayerId", "GameId");

                    b.ToTable("NBAPlayerGames");
                });

            modelBuilder.Entity("RotoMonster.Core.PerValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PlayerTypeId");

                    b.ToTable("PerValues");
                });

            modelBuilder.Entity("RotoMonster.Core.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bats")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<int?>("PickNumber")
                        .HasColumnType("int");

                    b.Property<int?>("RookieYear")
                        .HasColumnType("int");

                    b.Property<string>("Throws")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("RotoMonster.Core.PlayerAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerAliases");
                });

            modelBuilder.Entity("RotoMonster.Core.PlayerDefaultPosition", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("PlayerDefaultPositions");
                });

            modelBuilder.Entity("RotoMonster.Core.PlayerGameMissed", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NotPlayingDescription")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NotPlayingReason")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool?>("Played")
                        .HasColumnType("bit");

                    b.Property<bool?>("Started")
                        .HasColumnType("bit");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("PlayedGamesMissed");
                });

            modelBuilder.Entity("RotoMonster.Core.PlayerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DefaultPerTeam")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("PluralTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SingularTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlayerTypes");
                });

            modelBuilder.Entity("RotoMonster.Core.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int?>("PlayerTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerTypeId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("RotoMonster.Core.PositionSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PositionSources");
                });

            modelBuilder.Entity("RotoMonster.Core.PositionSourcePlayer", b =>
                {
                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int>("PositionSourceId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("SeasonId", "PositionSourceId", "PlayerId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("PositionSourcePlayers");
                });

            modelBuilder.Entity("RotoMonster.Core.PositionSourcePosition", b =>
                {
                    b.Property<int>("PositionSourceId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("PositionSourceId", "PositionId");

                    b.ToTable("PositionSourcePositions");
                });

            modelBuilder.Entity("RotoMonster.Core.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRegularSeason")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YahooId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("RotoMonster.Core.SeasonDivision", b =>
                {
                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.HasKey("SeasonId", "DivisionId");

                    b.HasIndex("DivisionId");

                    b.ToTable("SeasonDivisions");
                });

            modelBuilder.Entity("RotoMonster.Core.SeasonPlayer", b =>
                {
                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("SeasonId", "PlayerId", "PlayerTypeId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerTypeId");

                    b.ToTable("SeasonPlayers");
                });

            modelBuilder.Entity("RotoMonster.Core.SeasonTeam", b =>
                {
                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.HasKey("SeasonId", "TeamId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("TeamId");

                    b.ToTable("SeasonTeams");
                });

            modelBuilder.Entity("RotoMonster.Core.Sport", b =>
                {
                    b.Property<string>("DivisionTitle")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<bool>("UsesCategories")
                        .HasColumnType("bit");

                    b.Property<bool>("UsesPointsPerStat")
                        .HasColumnType("bit");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("RotoMonster.Core.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("RotoMonster.Core.UserLeague", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AutoEndDate")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoUpdate")
                        .HasColumnType("bit");

                    b.Property<bool>("ContinuousWaivers")
                        .HasColumnType("bit");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("DraftDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FantasyProviderId")
                        .HasColumnType("int");

                    b.Property<int>("GameLimit")
                        .HasColumnType("int");

                    b.Property<int>("IRSpots")
                        .HasColumnType("int");

                    b.Property<bool>("IsMoney")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSelectedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeagueType")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("LineupFrequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("MyProviderTeamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("MyTeamTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("NumberOfTeams")
                        .HasColumnType("int");

                    b.Property<int>("PlayersPerTeam")
                        .HasColumnType("int");

                    b.Property<string>("ProviderLeagueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("QualityGamesLimit")
                        .HasColumnType("int");

                    b.Property<bool>("SameDayTransactions")
                        .HasColumnType("bit");

                    b.Property<string>("ScoringSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("StartWeekday")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<bool>("TrackLeague")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.HasIndex("FantasyProviderId");

                    b.ToTable("UserLeagues");
                });

            modelBuilder.Entity("RotoMonster.Core.UserLeagueActiveRosterSpot", b =>
                {
                    b.Property<int>("UserLeagueId")
                        .HasColumnType("int");

                    b.Property<int>("ActiveRosterSpotId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPlayers")
                        .HasColumnType("int");

                    b.HasKey("UserLeagueId", "ActiveRosterSpotId");

                    b.HasIndex("ActiveRosterSpotId");

                    b.ToTable("UserLeagueActiveRosterSpots");
                });

            modelBuilder.Entity("RotoMonster.Core.UserLeagueCategory", b =>
                {
                    b.Property<int>("UserLeagueId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("PointsPerStat")
                        .HasColumnType("float");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("UserLeagueId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("UserLeagueCategories");
                });

            modelBuilder.Entity("RotoMonster.Core.UserLeagueTeam", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProviderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserLeagueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserLeagueId");

                    b.ToTable("UserLeagueTeams");
                });

            modelBuilder.Entity("RotoMonster.Core.UserLeagueTeamPlayer", b =>
                {
                    b.Property<long>("UserLeagueTeamId")
                        .HasColumnType("bigint");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("AuctionPrice")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIR")
                        .HasColumnType("bit");

                    b.Property<int>("PickNumber")
                        .HasColumnType("int");

                    b.HasKey("UserLeagueTeamId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("UserLeagueTeamPlayers");
                });

            modelBuilder.Entity("RotoMonster.Core.ActiveRosterSpotPosition", b =>
                {
                    b.HasOne("RotoMonster.Core.ActiveRosterSpot", "ActiveRosterSpot")
                        .WithMany("ActiveRosterSpotPositions")
                        .HasForeignKey("ActiveRosterSpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.Category", b =>
                {
                    b.HasOne("RotoMonster.Core.PlayerType", "PlayerType")
                        .WithMany()
                        .HasForeignKey("PlayerTypeId");

                    b.HasOne("RotoMonster.Core.Category", "WeightCategory")
                        .WithMany()
                        .HasForeignKey("WeightCategoryId");
                });

            modelBuilder.Entity("RotoMonster.Core.DisplayCategory", b =>
                {
                    b.HasOne("RotoMonster.Core.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.Draft", b =>
                {
                    b.HasOne("RotoMonster.Core.FantasyProvider", "FantasyProvider")
                        .WithMany()
                        .HasForeignKey("FantasyProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.DraftPlayer", b =>
                {
                    b.HasOne("RotoMonster.Core.Draft", "Draft")
                        .WithMany("DraftPlayers")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.FantasyProviderPlayer", b =>
                {
                    b.HasOne("RotoMonster.Core.FantasyProvider", "FantasyProvider")
                        .WithMany()
                        .HasForeignKey("FantasyProviderId");

                    b.HasOne("RotoMonster.Core.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("RotoMonster.Core.Game", b =>
                {
                    b.HasOne("RotoMonster.Core.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId");

                    b.HasOne("RotoMonster.Core.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId");

                    b.HasOne("RotoMonster.Core.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId");
                });

            modelBuilder.Entity("RotoMonster.Core.MLBHitterGame", b =>
                {
                    b.HasOne("RotoMonster.Core.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.MLBPitcherGame", b =>
                {
                    b.HasOne("RotoMonster.Core.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.PerValue", b =>
                {
                    b.HasOne("RotoMonster.Core.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.PlayerType", "PlayerType")
                        .WithMany()
                        .HasForeignKey("PlayerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.PlayerAlias", b =>
                {
                    b.HasOne("RotoMonster.Core.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("RotoMonster.Core.PlayerDefaultPosition", b =>
                {
                    b.HasOne("RotoMonster.Core.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.PlayerGameMissed", b =>
                {
                    b.HasOne("RotoMonster.Core.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.Position", b =>
                {
                    b.HasOne("RotoMonster.Core.PlayerType", "PlayerType")
                        .WithMany()
                        .HasForeignKey("PlayerTypeId");
                });

            modelBuilder.Entity("RotoMonster.Core.PositionSourcePlayer", b =>
                {
                    b.HasOne("RotoMonster.Core.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.SeasonDivision", b =>
                {
                    b.HasOne("RotoMonster.Core.Division", null)
                        .WithMany("SeasonDivisions")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Season", null)
                        .WithMany("Divisions")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.SeasonPlayer", b =>
                {
                    b.HasOne("RotoMonster.Core.Player", null)
                        .WithMany("SeasonPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.PlayerType", null)
                        .WithMany("SeasonPlayers")
                        .HasForeignKey("PlayerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Season", null)
                        .WithMany("SeasonPlayers")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.SeasonTeam", b =>
                {
                    b.HasOne("RotoMonster.Core.Division", null)
                        .WithMany("SeasonTeams")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Season", null)
                        .WithMany("SeasonTeams")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.Team", "Team")
                        .WithMany("SeasonTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.UserLeague", b =>
                {
                    b.HasOne("RotoMonster.Core.FantasyProvider", "FantasyProvider")
                        .WithMany()
                        .HasForeignKey("FantasyProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.UserLeagueActiveRosterSpot", b =>
                {
                    b.HasOne("RotoMonster.Core.ActiveRosterSpot", "ActiveRosterSpot")
                        .WithMany()
                        .HasForeignKey("ActiveRosterSpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.UserLeague", "UserLeague")
                        .WithMany("UserLeagueActiveRosterSpots")
                        .HasForeignKey("UserLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.UserLeagueCategory", b =>
                {
                    b.HasOne("RotoMonster.Core.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.UserLeague", "UserLeague")
                        .WithMany("UserLeagueCategories")
                        .HasForeignKey("UserLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.UserLeagueTeam", b =>
                {
                    b.HasOne("RotoMonster.Core.UserLeague", "UserLeague")
                        .WithMany("UserLeagueTeams")
                        .HasForeignKey("UserLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotoMonster.Core.UserLeagueTeamPlayer", b =>
                {
                    b.HasOne("RotoMonster.Core.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotoMonster.Core.UserLeagueTeam", "UserLeagueTeam")
                        .WithMany("UserLeagueTeamPlayers")
                        .HasForeignKey("UserLeagueTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
